/*
 *
 * UserAvatar constants
 *
 */

 export const GET_USER_AVATAR = 'GET_USER_AVATAR';
 export const GET_USER_AVATAR_SUCCESS = 'GET_USER_AVATAR_SUCCESS';
 export const GET_USER_AVATAR_ERROR = 'GET_USER_AVATAR_ERROR';
 export const SEND_USER_AVATAR = 'SEND_USER_AVATAR';
 export const SEND_USER_AVATAR_SUCCESS = 'SEND_USER_AVATAR_SUCCESS';
 export const SEND_USER_AVATAR_ERROR = 'SEND_USER_AVATAR_ERROR';
